spring.application.name=Yamini_ITE5435_FinalExam
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/huskyair

# Disable Thymeleaf cache for dev
spring.thymeleaf.cache=false

# API URLs for Reservation, Customer, Payment
api.reservation.url=http://localhost:3000/reservations
api.customer.url=http://localhost:3000/customers
api.payment.url=http://localhost:3000/payments